import { AGENT_NOTES_HEADING, AGENTS_REL_PATH, DEFAULT_TITLE, GENERATED_HEADING, NOTES_REL_PATH } from './template';

/**
 * The generated `.pacmon/AGENTS.md`: everything an AI agent needs to write the
 * agent layer of the notes file. Pacmon owns this file — it is regenerated from
 * here and never hand-edited, so the field vocabulary stays identical across
 * repositories and agents. Deterministic on purpose: no dates, no versions.
 */

export interface AgentFieldSpec {
  key: string;
  /** The question the field answers. */
  question: string;
  /** What one line of it should contain. */
  write: string;
  /** Core fields are filled whenever the agent can; the rest only when relevant. */
  core: boolean;
}

export const AGENT_FIELDS: readonly AgentFieldSpec[] = [
  {
    key: 'purpose',
    core: true,
    question: 'What job does it do here?',
    write: 'the package’s role in this project — what it is and why this repo uses it, one sentence',
  },
  {
    key: 'usage',
    core: true,
    question: 'Where and how is it wired in?',
    write: 'entry points, wrapper module, config; the rule for using it ("always through lib/http.ts")',
  },
  {
    key: 'constraint',
    core: true,
    question: 'What must not change?',
    write: 'a pin, a forbidden upgrade, a coordination requirement — the rule and its reason',
  },
  {
    key: 'verify',
    core: true,
    question: 'How do I check I did not break it?',
    write: 'a command or a flow: `vitest src/api`, "run the login e2e"',
  },
  {
    key: 'log',
    core: true,
    question: 'What happened, what was decided?',
    write: 'one dated event per line — added (by whom, version, PR), an upgrade attempt, a rejected proposal and why; carry a commit hash, PR or advisory id',
  },
  {
    key: 'verified',
    core: true,
    question: 'Which installed version were these notes checked against?',
    write: 'the version from the lockfile when you last confirmed the block is still true',
  },
  {
    key: 'risk',
    core: false,
    question: 'What does it cost or endanger?',
    write: 'a judgment — security exposure, native binary, licence obligation, maintenance state — not raw numbers',
  },
  {
    key: 'runtime',
    core: false,
    question: 'Where does it execute?',
    write: 'one of: server, client, build, dev, deploy',
  },
  {
    key: 'exposure',
    core: false,
    question: 'Does it handle untrusted input?',
    write: 'one of: untrusted-input, internal',
  },
  {
    key: 'bump-with',
    core: false,
    question: 'What must move with it?',
    write: 'packages that have to be upgraded together (peer pairs, plugin sets)',
  },
  {
    key: 'remove-when',
    core: false,
    question: 'When should it go?',
    write: 'the exit condition',
  },
  {
    key: 'alternatives',
    core: false,
    question: 'What could replace it?',
    write: 'only real decisions, dated, with a verdict: "fastify (rejected 2023-01: middleware ecosystem)"',
  },
  {
    key: 'owner',
    core: false,
    question: 'Who to ask?',
    write: 'a team, a person, a channel',
  },
  {
    key: 'status',
    core: false,
    question: 'Is it still here?',
    write: 'one of: dead, removal-planned, removed <YYYY-MM> — <reason>; absent means active',
  },
  {
    key: 'links',
    core: false,
    question: 'Sources?',
    write: 'changelog, docs, upstream issue, registry page — the specific ones, not the obvious',
  },
  {
    key: 'note',
    core: false,
    question: 'Anything else the next agent must know?',
    write: 'free text that fits no other field — one thought per line, never a measurement',
  },
];

export const STATUS_VALUES = ['dead', 'removal-planned', 'removed <YYYY-MM> — <reason>'] as const;
export const RUNTIME_VALUES = ['server', 'client', 'build', 'dev', 'deploy'] as const;
export const EXPOSURE_VALUES = ['untrusted-input', 'internal'] as const;

function table(fields: readonly AgentFieldSpec[]): string[] {
  return [
    '| Question | Field | One line of |',
    '|---|---|---|',
    ...fields.map((f) => `| ${f.question} | \`${f.key}:\` | ${f.write} |`),
  ];
}

export function agentsMdContent(eol = '\n'): string {
  const core = AGENT_FIELDS.filter((f) => f.core);
  const optional = AGENT_FIELDS.filter((f) => !f.core);
  const lines = [
    '# Dependency notes — instructions for AI agents',
    '',
    '<!-- Generated by Pacmon — do not edit. Re-run "Pacmon: Set Up AI Instructions" to refresh. -->',
    '',
    '## Where the notes live',
    '',
    `Every \`package.json\` in this repository has its notes in \`${NOTES_REL_PATH}\` next to it. In a monorepo the nearest one walking up from the package.json applies. The file starts with frontmatter:`,
    '',
    '```md',
    '---',
    'format: deps-notes/1',
    'lang: en',
    `agents: ${AGENTS_REL_PATH}`,
    '---',
    '```',
    '',
    'Field keys are always English. Write the values in the language given by `lang:`.',
    'Free text between the title and the first section holds repository-wide dependency rules; read it first.',
    '',
    '## The shape of a section',
    '',
    '```md',
    '## <exact package name from package.json, including @scope/>',
    '',
    'Text written by people. Do not touch it.',
    '',
    AGENT_NOTES_HEADING,
    '',
    '- key: value',
    '- key: value',
    '```',
    '',
    '- One `## name` section per direct dependency, in alphabetical order. `##` is reserved for package names.',
    `- One title, \`${DEFAULT_TITLE}\`. Inside a section the only heading is \`${AGENT_NOTES_HEADING}\`; anything else is plain text or a list.`,
    `- **The text right under the heading is written by people.** Never edit or delete it. Treat it as one of your sources — alongside the code, the git history, the registry and your own reasoning. If your block disagrees with it, the human text wins: fix your block and add a \`log:\` line saying so.`,
    `- **\`${AGENT_NOTES_HEADING}\` is yours.** Lower-case keys, one fact per line, keys may repeat (several \`constraint:\` or \`log:\` lines are normal). Keys outside the vocabulary below are flagged by Pacmon; if something fits none of them, write it as \`note:\` — never invent a key.`,
    '- Never write an empty field or a dash placeholder. If you have nothing true to say, leave the field out.',
    `- Write judgments, not measurements. Installed versions, licences, sizes and audit results belong to a future \`${GENERATED_HEADING}\` block that tools write — never write that block by hand.`,
    '- Revise, do not accumulate: correct a line instead of adding a contradicting one. `log:` is the exception — it is the history.',
    '- Keep the first human line short if you are ever asked to draft it: it is what shows next to the dependency in `package.json`.',
    '',
    '## Fields',
    '',
    'Fill these whenever you can:',
    '',
    ...table(core),
    '',
    'Add these only when they are true and non-obvious:',
    '',
    ...table(optional),
    '',
    `\`status:\` values: ${STATUS_VALUES.map((v) => `\`${v}\``).join(', ')}. A section whose status starts with \`removed\` is kept on purpose for a package that left \`package.json\`; Pacmon does not flag it as an orphan.`,
    `\`runtime:\` values: ${RUNTIME_VALUES.map((v) => `\`${v}\``).join(', ')}. \`exposure:\` values: ${EXPOSURE_VALUES.map((v) => `\`${v}\``).join(', ')}.`,
    '',
    '## When you touch a dependency',
    '',
    '- **Adding one:** open its section in the same commit, with at least `purpose:`. Say what you considered and why this one, in `alternatives:` or `log:`.',
    '- **Upgrading one:** read its `constraint:` and `verify:` lines first, then run what `verify:` says. Log the attempt with its outcome even if you reverted it — the next agent must not repeat it.',
    '- **Removing one:** keep the section and add `- status: removed <YYYY-MM> — <reason>`. Do not delete it.',
    '- **Trivial packages** (`@types/*`, tiny helpers): `purpose:` and, if it applies, `bump-with:` are enough.',
    '- Never remove the frontmatter or the header comment at the top of the file.',
    '',
    '## Example',
    '',
    '```md',
    '## express',
    '',
    'Do not upgrade to v5 — the auth middleware is incompatible (SEC-1301).',
    'Rate-limit settings live in `src/middleware/limits.ts`.',
    '',
    AGENT_NOTES_HEADING,
    '',
    '- purpose: HTTP framework; serves the public REST API and the webhook receiver',
    '- constraint: stay on ^4 — v5 changes router path matching (path-to-regexp v8) and the session API',
    '- verify: `vitest src/api` and the login e2e (`pnpm e2e:auth`)',
    '- log: 2026-03 agent tried 5.0.1, 14 auth tests failed, reverted (PR #402)',
    '- verified: 4.18.2',
    '```',
  ];
  return lines.join(eol) + eol;
}
